first = int(input("Enter first number : "))
sec = int(input("Enter second number : "))
print("Addition = ", first+sec)
print("Substraction = ", first-sec)
print("Multiplication = ", first*sec)
print("Division = ", first/sec)
print("floor division = ", first//sec)
print("Modulus = ", first%sec)